# Generated by Django 2.1.3 on 2018-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181222_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text="enter the book's natural language", max_length=200),
            preserve_default=False,
        ),
    ]
